
[webservers]
web-1 ansible_host=51.250.72.54 fqdn=fhmv19imksm667bk2nbr.auto.internal
web-2 ansible_host=111.88.251.131 fqdn=fhmsb5h6kcubq17q1pbh.auto.internal

[databases]
main ansible_host= fqdn=fhms8qqaakdrjgqh254r.auto.internal
replica ansible_host= fqdn=fhmru8ekljiq7ii73rhk.auto.internal

[storage]
storage ansible_host=89.169.147.74 fqdn=fhm7vgb4eth38bluqgno.auto.internal
